@startuml C4_Container
  !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

  LAYOUT_WITH_LEGEND()

  title [Diagrama de Containers] - Sistema para Gestão Condominial

  Person(admin, "Administrador do Sistema")
  Person(condoUser, "Usuário do Condomínio")

  System_Boundary(sistema, "Sistema de Gestão Condominial") {
    Container(api, "Backend API", "Node.js (TypeScript)", "Exposição de endpoints RESTful, seguindo Clean Architecture")
    Container(db, "Banco de Dados Relacional", "PostgreSQL", "Armazena dados do sistema, como usuários, comunicados, documentos etc.")
  }

  System_Ext(emailSystem, "Sistema de E-mail", "Serviço de envio de notificações")
  System_Ext(docStorage, "Armazenamento de Documentos", "Serviço externo para guardar atas e documentos")

  Rel(admin, api, "Gerencia e administra via")
  Rel(condoUser, api, "Interage com o sistema via")
  Rel(api, db, "Lê e grava dados")
  Rel(api, emailSystem, "Envia e-mails de notificação")
  Rel(api, docStorage, "Salva e acessa documentos via")
@enduml
